%This file was automatically generated by --Generate_FK--
%The input vector is:
%u=[q1;q2;q3;q4;L1;L2;;Ln ]
function X=FK_robot(u)
q1=u(1);
q2=u(2);
q3=u(3);
q4=u(4);
L1=u(5);
L2=u(6);
Ln=u(n+4);


% TODO use the symbolic equation to compute the Forward Kinematics of the
% end-effector POSE
X=zeros(6,1);
